name: Slack Notification Demo

on: 
  pull_request:
    types: [closed]
  push:
   branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testing
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Commit Message
        SLACK_USERNAME: slackBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
