name: Slack Notification Demo

on: push

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testing
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MSG_AUTHOR: $GITHUB_ACTOR
        SLACK_TITLE: Commit Message
        SLACK_USERNAME: slackBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
