name: Send commit message to Slack

on:
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send commit message to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          channel_id: '#general'
          message: "New commit: ${{ github.event.head_commit.message }}"
          username: GitHub Actions
