name: Send commit message on merge to Slack

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  send-message:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send commit message to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_bot_token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          channel_id: your-channel-id
          message: "Merged commit: ${{ github.event.pull_request.head.sha }} - ${{ github.event.pull_request.title }}"
          username: GitHub Actions
